#theme: jekyll-theme-slate
title:  ELG 7172B (EACJ 5600) Principles of Data and Error Analysis in Engineering Measurements
description: ELG7172B course website
baseurl: ''
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - contents
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
